language: java

jdk:
  - oraclejdk8

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  app: mjerilo
  api_key:
    secure: PnGrpF1pLzoTtBTFTElKV6Ef2lz7Sf6wGfz9NxS/8b8FbLCsDcbsb7Vmy+GfThRW5mWIAYk0pfT/xgCCDYeyogZrrY5rmTCRFOmCuUoCEtYKr/rExDkSt8R4fRESzqofiqg1OEPQR81ebe7cgNkqj32cckaOJf6kgA/q53Y8wtF/dpT4ApUAC6OKFuzzIxaQB0QO2ALnljQ629M7Rw7bP+bs5scz0Gy8WpZ5M9yBwnrGU4rFl2sOG2HU+R56q8QQsiMKyFTayxeZNRp64c9hWw2COzCe+kSjKeQ3d18r7fS68TIvLw26RPApe/hcfmtvAo057kOrP5crsLC+WA8XtlVhkjzGhPEDPbggmI1TlgbCOI2rvBw1yW0mKHvVurpfNzGIbpkhtS+X9oJe5UPPtClTZS2Aw1WK1eads5Aqap32ptph8wS7qXCrpIMJN7zOFfbjk/24N03Vij6iIh1KiPzfZWKNE9Q0FVClk/wbOKA83fsZWPSs3nArhsy8n0PQZZlf6wZtF8I8MHsUYI8HCtoypPJAtrh+YXRt1KO3q9Y+iwJtFahqqez+wUkgheej+xwt+n2w3XGNoEF8lXUQ55jNaiQ8364x11dqsyY6q+eT0ffge5BdV/I8an9oXC8jlh2KCx86roLp9xLHXiFoRAyBw5tku/0HrUkV8MUGq64=
